### ISSUE TITLE
vss2iotea adapter does not start correctly

### ISSUE THREAD

**Issue by wenwenchenbosch** [GENIVI/iot-event-analytics#59]
I try to use the vss2iotea adapter docker images, but I got the following error message:

```
docker run -it --log-opt max-size=1m --log-opt max-file=5 --network="host" --restart=unless-stopped --name=vss2iotea-adapter -v config:/app/docker/vss2iotea/config vss2iotea-adapter-amd64 /bin/sh
/app # node docker/vss2iotea/
.Dockerfile.amd64.swp  Dockerfile.arm64       config/
Dockerfile.amd64       README.md              index.js
/app # node docker/vss2iotea/index.js 
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module ''./util/mqttClient'
Require stack:
- /app/src/core/protocolGateway.js
- /app/src/core/metadataManager.js
- /app/src/adapter/vss/vss.adapter.js
- /app/docker/vss2iotea/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at new ProtocolGateway (/app/src/core/protocolGateway.js:23:28)
    at new Talent (/app/src/core/talent.js:102:19)
    at new VssAdapter (/app/src/adapter/vss/vss.adapter.js:60:9)
    at Object.<anonymous> (/app/docker/vss2iotea/index.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/src/core/protocolGateway.js',
    '/app/src/core/metadataManager.js',
    '/app/src/adapter/vss/vss.adapter.js',
    '/app/docker/vss2iotea/index.js'
  ]
}
```

I found `mqttClient.js` under `/app/src/core/util`:
```
/app/src/core/util # ls
arrayPatternMatcher.js    jsonModel.js
clone.js                  jsonQuery.js
equals.js                 logger.js
errorMessageFormatter.js  mqttClient.js
featureGraph.js           talentIO.js
featureMap.js             validatePlatformId.js
```

**Comment by wenwenchenbosch** [comment]
I found out, that here a superfluous `'` 
https://github.com/GENIVI/iot-event-analytics/blob/bf79d8302e9b08c9eb5ea7640368fb0e00f8fc58/docker/vss2iotea/config/config.json#L7

**Comment by wenwenchenbosch** [comment]
but now a new error:

```
2021-04-29T09:08:25.986Z  ALWAYS [vss-adapter-da24d5fd-2b58-450b-95da-612bba530886.MqttClient-a2bfa29e] : *****INFO***** Using topic namespace iotea/
/app/src/core/protocolGateway.js:162
        throw new Error(`Should use platform protocol only, but no platform adapter found`);
        ^

Error: Should use platform protocol only, but no platform adapter found
    at Function.validateConfiguration (/app/src/core/protocolGateway.js:162:15)
    at new ProtocolGateway (/app/src/core/protocolGateway.js:5:25)
    at new MetadataManager (/app/src/core/metadataManager.js:44:19)
    at new VssAdapter (/app/src/adapter/vss/vss.adapter.js:63:32)
    at Object.<anonymous> (/app/docker/vss2iotea/index.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

**Comment by llakie** [comment]
It's both related to issues in the configuration file. Will be fixed in an upcoming PR. I will inform you when it's done :)
PR is #65

**Comment by wenwenchenbosch** [comment]
thanks
